version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - db-net

  graph-db:
    image: neo4j:5.26.16
    container_name: graph_db
    restart: unless-stopped
    ports:
      - "${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}"
      - "${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}"
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - ./database/graph_db/neo4j.conf:/config/neo4j.conf
    networks:
      - db-net

  vector-db:
    image: semitechnologies/weaviate:1.34.0
    container_name: vector_db
    restart: on-failure:0
    ports:
      - "${WEAVIATE_PORT}:${WEAVIATE_PORT}"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'weaviate-node'
    volumes:
      - weaviate-data:/var/lib/weaviate
      - ./database/vector_db/config.json:/var/lib/weaviate/config.json
    networks:
      - db-net

volumes:
  postgres-data:
    driver: local
  neo4j-data:
    driver: local
  neo4j-logs:
    driver: local
  weaviate-data:
    driver: local

networks:
  db-net:
    driver: bridge
