services:
  backend:
    build:
      context: ./apps/sao_chatbot_backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: unless-stopped
    env_file:
      - ./apps/sao_chatbot_backend/.env
    environment:
      SQL_DATABASE_URL: ${SQL_DATABASE_URL}
    depends_on:
      - redis
    networks:
      - app-net

  frontend:
    build:
      context: ./apps/sao_chatbot_frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"
    env_file:
      - ./apps/sao_chatbot_frontend/.env.production
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

